server:
  port: 8080

mybatis:
  typeAliasesPackage: com.shangda.tourism.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  mvc:
    static-path-pattern: /**

  datasource:
    url: jdbc:mysql://42.193.110.10:3306/tourism?&serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    username: mengfanyi
    password: 123456a!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    host: smtp.qq.com
    port: 465
    username: 1759269294@qq.com
    password: tgazgpfppvnrciad
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: true


tourism:
  path:
    domain: http://42.193.110.10:8080